### ISSUE TITLE
Update Develop Contributor Notes

### ISSUE THREAD

**Issue by QuinnHe** [ml5js/ml5-website-v02-docsify#134]
After soft launch, we can update `Develop Contributor Notes` page to align with the next-gen

**Comment by MOQN** [comment]
This has also been addressed [here](https://github.com/ml5js/ml5-next-gen/pull/73).

@ziyuan-linn @gohai Could you please assist with this?

**Comment by QuinnHe** [comment]
done with #155 , closed
