### ISSUE TITLE
Add an announcement for old website and link to FAQ

### ISSUE THREAD

**Issue by QuinnHe** [ml5js/ml5-website-v02-docsify#142]
FAQ talking about older website: https://docs.ml5js.org/#/welcome/faq?id=what-happened-to-older-ml5js-releases

**Comment by shiffman** [comment]
This is fantastic! I think it would be nice to add a bit more info about how it works to reference the different versions. Here are some ideas, I can open a PR if this sounds good to you?

------

If your existing code references `@latest`, you may encounter compatibility issues with newer versions of ml5.js.  For older code, navigate to `index.html` in the p5.js web editor (or whatever code editor you are using) and adjust the scirpt tag to reference ml5@0.12.2. If you were using an even older version, replace `0.12.2` with the version number you were previously using.

```html
   <script src="https://unpkg.com/ml5@0.12.2/dist/ml5.min.js"></script>
```

For using the latest release of ml5.js with the new, updated models and API, you can reference `1.0.1`.

```html
   <script src="https://unpkg.com/ml5@1.0.1/dist/ml5.min.js"></script>
```
 
You can also use `ml5@1` which will automatically load future 1.x releases, but this could possibly introduce things that would alter the behavior of your sketch.

**Comment by shiffman** [comment]
I created this pinned issue (thanks for the draft text @ziyuan-linn!), shall we reproduce the text in the FAQ on the site? https://github.com/ml5js/ml5-next-gen/issues/167

**Comment by QuinnHe** [comment]
Thanks Dan @shiffman ! Yes, will work on a PR before our next regroup. cc @MOQN

**Comment by MOQN** [comment]
Yes!!

**Comment by MOQN** [comment]
Yes!! It will be applied by the next group meeting.

**Comment by QuinnHe** [comment]
Updates: modified the FAQ page to reflect Dan's text at [https://docs.ml5js.org/#/welcome/faq?id=what-happened-to-older-ml5js-releases)

Todo: add an announcement to link to the FAQ cc @MOQN @alanvww

**Comment by MOQN** [comment]
Update: Announcement banner was added to [the main page](https://ml5js.org/), and linked to the FAQ.

**Comment by QuinnHe** [comment]
Everything is updated. Close the issues.
