### ISSUE TITLE
missing neuroevolution functions from docs

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v02-docsify#143]
I'm opening an issue with info and resources about neuroevolution for the website documentation that @sharellb plans to work on! (I just sent an email but realized maybe it makes more sense to track here.)

I cover neuroevolution in [Chapter 11 from Nature of Code](https://natureofcode.com/neuroevolution/). (Chapters 9 and 10 have the base material about genetic algorithms and neural network fundamentals).

The functions I added to ml5.neuralNetwork to make neuroevolution "easier" are [`crossover()` and `mutate()`](https://github.com/ml5js/ml5-next-gen/blob/main/src/NeuralNetwork/NeuralNetwork.js#L240). I think these are missing from the docs and there might be other elements also missing? I don't remember as I hacked all this together while writing the book under tight deadlines!

There is also this discussion with @ziyuan-linn which may be relevant:
https://github.com/ml5js/ml5-next-gen/pull/138

Finally, I highly recommend [the work on David Ha](https://otoro.net/ml/) for a deeper dive into neuroevolution!

**Comment by sharellb** [comment]
Awesome, thanks so much @shiffman! I plan to take a look at these starting next week and track questions/updates here

**Comment by QuinnHe** [comment]
Hi Moon @MOQN, maybe we could discuss whether we add neuroevolution to NN page, or have a dedicated page for it. 

Some ideas come to my mind:
1. list crossover() and mutate() on NN page, and add lightbulb tips saying "this is related to neuroevolution, and please check out our neuroevolution page to learn more"
2. create a neuroevolution page that has the same formats as other pages, also has demo, example, step by step guidance, and then link to Dan's chapter

OR
2. create a neuroevolution page that will be included in "Learn" section, make it as an advanced topic. And within that page, we can link to Dan's chapter

OR
2. we don't have a dedicated page for neuroevolution, we can simply link to Dan's chapter within the Methods of NN

cc @shiffman @sharellb

**Comment by MOQN** [comment]
@QuinnHe Thanks for addressing this! I am currently indecisive about whether to have a reference page or a page in the Learn section. Let's discuss it (and Gottfried's suggestion) in a webteam meeting?

**Comment by shiffman** [comment]
I don't feel strongly about this either way but I think it's ok to go with:

> we don't have a dedicated page for neuroevolution, we can simply link to Dan's chapter within the Methods of NN

It's not clear to me whether people will use the neuroevolution features of ml5.js broadly or if it's a niche thing just for the nature of code book readers. So I think just documenting them and linking out to my materials is a fine way to start! And if we get a lot of questions or see a lot of neuroevolution projects maybe we build it out more?

**Comment by QuinnHe** [comment]
> I don't feel strongly about this either way but I think it's ok to go with:
> 
> > we don't have a dedicated page for neuroevolution, we can simply link to Dan's chapter within the Methods of NN
> 
> It's not clear to me whether people will use the neuroevolution features of ml5.js broadly or if it's a niche thing just for the nature of code book readers. So I think just documenting them and linking out to my materials is a fine way to start! And if we get a lot of questions or see a lot of neuroevolution projects maybe we build it out more?

Sounds good!! On it, will have them ready before next regroup

**Comment by QuinnHe** [comment]
done, please review #154 @MOQN

**Comment by QuinnHe** [comment]
Resolved by #154 .
