### ISSUE TITLE
Fix typo on BodyPose reference docs from "HandPose" to "BodyPose"

### ISSUE THREAD

**Issue by sharellb** [ml5js/ml5-website-v02-docsify#148]
The BodyPose reference docs set up section should say we're using BodyPose vs "HandPose"
 <img width="835" alt="Screen Shot 2024-07-19 at 9 41 21 PM" src="https://github.com/user-attachments/assets/0c6c7c09-ac5a-4d3f-96f3-97dcf54183ec">

**Comment by MOQN** [comment]
Thank you for spotting this!

**Comment by sharellb** [comment]
Thanks @MOQN! I was following the ReadMe to open up a PR and I'm a member of the ml5 org but seems like I still don't have the permissions to push a new branch up to the repo. I can follow the instructions for forking the repo to create a pull request as a workaround but wanted to check if I'm missing a step or if that's expected

**Comment by MOQN** [comment]
@sharellb I updated your access as "Write." Please feel free to create a branch and open a PR!

I am happy to fix the typo too :D

**Comment by sharellb** [comment]
Thanks @MOQN! That worked and I was able to create a branch and make a PR :D
