### ISSUE TITLE
Update BodySegmentation MaskType option  from "body" to "person" in Methods section

### ISSUE THREAD

**Issue by sharellb** [ml5js/ml5-website-v02-docsify#149]
When using "body" as a maskType, gives a warning in the console to use "person" instead.
<img width="581" alt="bodySegmentation-masktype" src="https://github.com/user-attachments/assets/0325ed89-7989-44f8-913d-806597882dd8">

The two places I saw referenced in the docs to update were in the parameter options code example and maskType definitions on the[ BodySegmentation](https://docs.ml5js.org/#/reference/body-segmentation?id=ml5bodysegmentation) reference page. 
<img width="776" alt="Screen Shot 2024-07-19 at 10 39 42 PM" src="https://github.com/user-attachments/assets/22c6cba6-9fa0-4457-a4ff-deddf35ccacd">

**Comment by QuinnHe** [comment]
Thanks @sharellb ! Well noted! cc @MOQN

**Comment by MOQN** [comment]
Thank you @sharellb !

**Comment by QuinnHe** [comment]
Thanks @alanvww !!!! Will go ahead and merge
