### ISSUE TITLE
add favicon

### ISSUE THREAD

**Issue by QuinnHe** [ml5js/ml5-website-v02-docsify#157]
we probably need to add favicon so that it shows at the tab/google search results. cc @MOQN @alanvww 

<img width="246" alt="Screenshot 2024-07-31 at 9 52 43 PM" src="https://github.com/user-attachments/assets/d9eb601d-1975-4129-800a-604eb46a6d9a">

<img width="753" alt="Screenshot 2024-07-31 at 9 52 56 PM" src="https://github.com/user-attachments/assets/76b4edcc-f407-4718-8f63-3c3d843ff3f8">

**Comment by alanvww** [comment]
It should be an easy fix. Is it ok if we just keep it the same style like the previous site? ![CleanShot 2024-07-31 at 22 56 46@2x](https://github.com/user-attachments/assets/8d554081-181c-495e-bb2a-aa423fae10c3)

**Comment by QuinnHe** [comment]
> It should be an easy fix. Is it ok if we just keep it the same style like the previous site? ![CleanShot 2024-07-31 at 22 56 46@2x](https://private-user-images.githubusercontent.com/10086000/354060755-8d554081-181c-495e-bb2a-aa423fae10c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODE0MTUsIm5iZiI6MTcyMjQ4MTExNSwicGF0aCI6Ii8xMDA4NjAwMC8zNTQwNjA3NTUtOGQ1NTQwODEtMTgxYy00OTVlLWJiMmEtYWE0MjNmYWUxMGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAyNTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYWM4NDFjNTE3ZTIxNWQxNWY5MWE1YWM1M2I4ZGJhMDE1MWE3NjQ1NGYwNDc3MmU4OTU2OTRmMzA4Y2FiMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TEr6yf2lCBnOsrLZAP640cBbovr4zLmBYgeKlKX8QtY)

Haha looks good to me! But let me @MOQN here, please chime in here for styles and visuals :)

**Comment by alanvww** [comment]
Yea I am open to have a new favicon since it looks like this icon is not showing up on our site anymore. Just drop me an image here and I will take care of it :D

**Comment by MOQN** [comment]
@QuinnHe @alanvww Thank you! I will share a favicon image(s) with Alan.

**Comment by MOQN** [comment]
@alanvww I sent an email, including a set of multiple images that can be bundled into a single ICO file. Please feel free to use them in any way! The image sizes are:
- 16x16 px
- 32x32 px
- 48x48 px
- 64x64 px
- 96x96 px
- 128x128 px
- 192x192 px
- 256x256 px
- 512x512 px

Please note that the image at 16x16 pixels looks slightly different; since it's too small, I had to retouch it pixel by pixel with the pencil tool.

**Comment by alanvww** [comment]
> @alanvww I sent an email, including a set of multiple images that can be bundled into a single ICO file. Please feel free to use them in any way! The image sizes are:
> 
> - 16x16 px
> 
> - 32x32 px
> 
> - 48x48 px
> 
> - 64x64 px
> 
> - 96x96 px
> 
> - 128x128 px
> 
> - 192x192 px
> 
> - 256x256 px
> 
> - 512x512 px
> 
> 
> 
> Please note that the image at 16x16 pixels looks slightly different; since it's too small, I had to retouch it pixel by pixel with the pencil tool. 

Thanks Moon! Will work on it now.
