### ISSUE TITLE
New OG image

### ISSUE THREAD

**Issue by alanvww** [ml5js/ml5-website-v02-docsify#160]
As we talked about in #159 , we’d like to update the OG image with the illustrations from the homepage. Here are a few different versions I made:
![CleanShot 2024-08-06 at 00 47 51@2x](https://github.com/user-attachments/assets/32a52d03-308b-4f33-bd63-0c0fbf29c6b7)
Let me know what you think! 😊 cc @MOQN @shiffman @QuinnHe @myrahsa @XiaozaoWang

**Comment by alanvww** [comment]
Figma file: https://www.figma.com/design/Qs7H9qPBgmAkqgxrMyQd9N/ml5-OG-Image?node-id=0-1&t=bbXAqwIJSPAKOX2l-1

**Comment by MOQN** [comment]
@alanvww Thank you! I vote for the second one _White Background - No Outline_.

**Comment by alanvww** [comment]
> @alanvww Thank you! I vote for the second one _White Background - No Outline_.
> 
> I've sent the illustration images in grayscale via email, just in case you want to explore some drafts with the purple background.

Hey Moon, I tried a few designs with the purple background and the greyscale images. I think they are too bland compare with those above. Let's go with the _White Background - No Outline_ for now :D
