### ISSUE TITLE
Typos in `handPose` and `bodyPose` Methods section

### ISSUE THREAD

**Issue by jackbdu** [ml5js/ml5-website-v02-docsify#163]
In the [Methods section of `handPose` Reference](https://docs.ml5js.org/#/reference/handpose?id=methods), `handPose` is currently referred to as `handpose`.

**Comment by alanvww** [comment]
> In the [Methods section of `handPose` Reference](https://docs.ml5js.org/#/reference/handpose?id=methods), `handPose` is currently referred to as `handpose`.

Thanks Jack! Will include it into the latest docs update :)

**Comment by MOQN** [comment]
@jackbdu Nice catch! Thank you.
@alanvww I just fixed the typo! [PR #164](https://github.com/ml5js/ml5-website-v02-docsify/pull/164)

**Comment by jackbdu** [comment]
@MOQN Thanks for the quick response! Sorry I might have not made it super clear, it seems all occurrences of `handPose` in the section are currently `handpose`.

**Comment by jackbdu** [comment]
In addition, in bodyPose > Methods > Parameters > options, there is a missing comma and a missing letter R near the end of `modelType` line:
`modelType: "MULTIPOSE_LIGHTNING", // "MULTIPOSE_LIGHTNING", "SINGLEPOSE_LIGHTNING", or "SINGLEPOSE_THUNDER"`

**Comment by alanvww** [comment]
@jackbdu thanks Jack🥲 fixing them now!!!
