### ISSUE TITLE
Modify legacy web editor examples to include the old library

### ISSUE THREAD

**Issue by gohai** [ml5js/ml5-website-v02-docsify#167]
Hi 👋,

I noticed that the linked object detection example on the "old" (legacy) documentation website wasn't running, as it was including `ml5@latest` rather than the versioned one.

Not sure how much use there is to keep those examples operational, but since the fix is very straightforward, I am thinking that it might be worth the hassle. (Happy to take this on if someone can facilitate my access to the `ml5` user on the p5 web editor.)

Thanks!

**Comment by shiffman** [comment]
Thanks for catching this @gohai! @ziyuan-linn can we manually fix old examples or will this conflict with the automated process of updating examples? @gohai I can DM you the web editor credentials.

**Comment by ziyuan-linn** [comment]
Manually fixing old examples should not conflict with the automated process! The automated script only looks for matching sketch names and the old examples are not touched.

**Comment by alanvww** [comment]
Hi @gohai, thanks for the heads up on this today! As I manage the https://github.com/ml5js/ml5-archive-docs repo, I have changed all the related tutorial content to use the fixed version `ml5@0.12.2`. I do realize there are a lot of sketches in the web editor are still using `ml5@latest` and manually fixing each of them will be hard to do.

I am still working on the scripts to update them with automation and will need a few test runs. Can I get back to you in the next two days? I will email you about my progress and my goal is to get it done ASAP. If there is a specific example you want to change now, please do so as well!

**Comment by alanvww** [comment]
I’ve just ran the update scripts, and now, most of the old ml5 examples available in the web editor should be using `ml5@0.12.2` :D

Please let me know if there are any issues!
