### ISSUE TITLE
Update bodyPose skeleton diagram url 

### ISSUE THREAD

**Issue by QuinnHe** [ml5js/ml5-website-v02-docsify#169]
<img width="775" alt="Screenshot 2024-08-28 at 9 48 16 PM" src="https://github.com/user-attachments/assets/8651bc96-4f68-4f11-b773-98f3372dfad1">
<img width="862" alt="Screenshot 2024-08-28 at 9 48 09 PM" src="https://github.com/user-attachments/assets/f29730cf-c100-4c08-9d28-431f79f14c69">

Instead of using url to third-party sources, maybe we should consider saving the diagrams as static assets to our own repo. Maybe we can also consider drawing our own version of the keypoint diagram. cc @MOQN  @alanvww @XiaozaoWang @myrahsa

**Comment by alanvww** [comment]
Yes, the simplest way would be to have them as static images in the `docs/assets` folder. I’ll try to recover the images so it won't keep showing the broken link. It would be fantastic if we could have an updated version of them tho :D

**Comment by alanvww** [comment]
The diagram issue has been resolved in the pull request above. However, we should also consider updating the images in the “Getting Started” section with the most recent update to the p5 web editor. The UI is slightly different.
