### ISSUE TITLE
Issue with TM example

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v02-docsify#173]
Similar to #171 I found that [the example linked from the TM page](https://docs.ml5js.org/#/reference/image-classifier-tm?id=examples) on the website goes to:

https://editor.p5js.org/ml5/sketches/ImageModel_TM

The above sketch is using the old ml5.js and old syntax. I made a corrected / updated version of the example here for the class I am teaching today so there is no urgency, but we should fix at some point!

https://editor.p5js.org/ima_ml/sketches/vOSSEZwGf

**Comment by MOQN** [comment]
Thank you so much for pointing this out, @shiffman! We will update it shortly.

**Comment by QuinnHe** [comment]
Resolved with #177 , both the link and text of the documentation have been updated accordingly. cc @MOQN @shiffman
