### ISSUE TITLE
New Video Tutorial on BodyPose

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v02-docsify#189]
### Update Type

Content

### Description

In case you would like to incorporate this into the site anywhere or just for reference, here is a new video tutorial on the BodyPose model!

* https://youtu.be/T99fNXTUUaQ
* https://thecodingtrain.com/tracks/ml5js-beginners-guide/ml5/7-bodypose/pose-detection (link will be live in 5-10 minutes)

![ML5-Pose-Detection-Thumbnail-A](https://github.com/user-attachments/assets/e1c67b22-1154-453d-9f8e-bf01a2348541)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MOQN** [comment]
Thank you so much @alanvww for update the reference pages with the tutorial!

I am reopening this to add it to the community post.

**Comment by alanvww** [comment]
> Thank you so much @alanvww for update the reference pages with the tutorial!
> 
> I am reopening this to add it to the community post.

Thanks Moon! Sorry, I didn't realize my PR had closed the issue. If I have time later today, I will also help add it to the community post!

**Comment by MOQN** [comment]
The video tutorial is included ([PR#39](https://github.com/ml5js/ml5-website-v02-gatsby/pull/39)) and featured on the Home page.
