### ISSUE TITLE
Incorrect TM image classificaiton example

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website-v02-docsify#201]
### Update Type

Code Example

### Description

The example on this page https://docs.ml5js.org/#/reference/image-classifier-tm should link to this example https://editor.p5js.org/ml5/sketches/VvGXajA36. Discovered this as part of investigating https://github.com/ml5js/ml5-next-gen/issues/236

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alanvww** [comment]
Fixed :D
Thanks @leey611 💜
