### ISSUE TITLE
Trial Issue

### ISSUE THREAD

**Issue by apoorva-a98** [ml5js/ml5-website-v02-docsify#26]
Starting the a11y audit.

**Comment by shiffman** [comment]
The issue is on this page:
https://ml5js.github.io/ml5-website-v02-docsify/#/reference/handpose


here is the snippet causing the issue:

```html
<a href="#start-of-content" class="p-3 color-bg-accent-emphasis color-fg-on-emphasis show-on-focus js-skip-to-content">Skip to content</a>
```

The fix I would propose is blah blah blah

**Comment by sproutleaf** [comment]
Closing this issue since I've moved all the issues in https://docs.google.com/document/d/1zqCGnob98Jt66oT2JRAU64EtnZCyhzZapTjprQOHSCg/edit to separate new issues in the repo
