### ISSUE TITLE
[a11y] Skipped heading level

### ISSUE THREAD

**Issue by sproutleaf** [ml5js/ml5-website-v02-docsify#30]
**→ Describe the issue, including on which page it can be found**
Skipped heading level on `Getting Started` page. `Getting Started` is h1 and the next heading `Try ml5.js online` is h3.

**→ Screenshots or relevant documentation**
<img width="773" alt="part of getting started page" src="https://github.com/ml5js/ml5-website-v02-docsify/assets/116130954/10570712-6b9e-4b3d-9345-d0a42cc0c4a6">

**→ Example snippet causing the issue**
https://github.com/ml5js/ml5-website-v02-docsify/blob/f03bdb1c0dd41fe81a2c72b32336f80e740d5317/docs/README.md?plain=1#L6C1-L6C1

**→ Potential solution and a11y standard it will meet (AA/AAA)**
Need to add an h2 level heading that categorizes all of the h3 headings that are coming under. Will meet A, AA

**→ Low priority? (Y/N)**
N

**Comment by QuinnHe** [comment]
added h2 "Create an Empty Project"
