### ISSUE TITLE
[a11y] Redirect link not descriptive

### ISSUE THREAD

**Issue by sproutleaf** [ml5js/ml5-website-v02-docsify#31]
**→ Describe the issue, including on which page it can be found**
Uses `here` (multiple occurrences), redirection link is not descriptive on `Getting Started` page

**→ Screenshots or relevant documentation**
<img width="351" alt="Screenshot 2023-11-25 at 8 30 38 PM" src="https://github.com/ml5js/ml5-website-v02-docsify/assets/116130954/02654d31-eef5-4009-8749-0cde0815c002">

**→ Example snippet causing the issue**
https://github.com/ml5js/ml5-website-v02-docsify/blob/f03bdb1c0dd41fe81a2c72b32336f80e740d5317/docs/README.md?plain=1#L7

**→ Potential solution and a11y standard it will meet (AA/AAA)**
Attach the link to “next steps to open ml5.js online” instead of “here”, will meet A

**→ Low priority? (Y/N)**
N

**Comment by QuinnHe** [comment]
updated the links with descriptive texts.
