### ISSUE TITLE
[a11y] Unicode characters

### ISSUE THREAD

**Issue by sproutleaf** [ml5js/ml5-website-v02-docsify#32]
**→ Describe the issue, including on which page it can be found**
We use a variety of unicode characters throughout the website. How they are read aloud is dependent on the screen reader the user is using. For example, VoiceOver reads it as an “electric light bulb”. Although there aren't any specific guidelines for using Unicode emojis within the text, the visual description of the emoji does not align with the rest of the text and may confuse a screen reader user. Ideally, we’d set them as decorative images/icons. Happens multiple times on `Getting Started` page.

**→ Screenshots or relevant document
<img width="400" src="https://github.com/ml5js/ml5-website-v02-docsify/assets/116130954/2500eb0d-f76c-4fdc-aad1-88e66c1f4e03">
ntation**
<img width="400" src="https://github.com/ml5js/ml5-website-v02-docsify/assets/116130954/d895ef35-e8a8-4faa-81cd-b82255409e22">

**→ Example snippet causing the issue**
https://github.com/ml5js/ml5-website-v02-docsify/blob/f03bdb1c0dd41fe81a2c72b32336f80e740d5317/docs/README.md?plain=1#L9

**→ Potential solution and a11y standard it will meet (AA/AAA)**
If we want the emoji, we could look into adding it as an icon and setting it as a “decorative image” so the screen reader skips over it.

`<img src="topinfo_bg.png" alt="">`
OR 
`<img src="your-image-source.jpg" alt="Description of the image" aria-hidden="true">`

**→ Low priority? (Y/N)**
N

**Comment by QuinnHe** [comment]
convert emojis on getting started to images
