### ISSUE TITLE
Reformat lightbulb tip into a more obvious style

### ISSUE THREAD

**Issue by QuinnHe** [ml5js/ml5-website-v02-docsify#77]
Hi @MOQN , now as I review & rewrite the content, I feel it will make more sense if we add a transparent bounding box around those lightbulb tip instead of just use `_` to italicize it.

I'm thinking something like this:
<img width="531" alt="Screenshot 2024-06-02 at 6 12 13 PM" src="https://github.com/ml5js/ml5-website-v02-docsify/assets/31847981/40c539dc-8c43-4048-988b-bb0d36e62abc">

**Comment by MOQN** [comment]
Wow, I also have had a note about the same thing! Let's discuss it during the meeting.

**Comment by QuinnHe** [comment]
Resolved by [PR#85](https://github.com/ml5js/ml5-website-v02-docsify/pull/85).

**Comment by MOQN** [comment]
I am still working on the styles - I will report it here and close once it's done.

**Comment by MOQN** [comment]
The styles were updated. Please view [PR#94](https://github.com/ml5js/ml5-website-v02-docsify/pull/94).

<img width="774" alt="Screenshot 2024-06-18 at 9 26 00 AM" src="https://github.com/ml5js/ml5-website-v02-docsify/assets/2150896/bf14e43e-3dca-458c-bae5-c2fb903eeffb">
