### ISSUE TITLE
Add a FAQ talking about archived ml5 methods

### ISSUE THREAD

**Issue by QuinnHe** [ml5js/ml5-website-v02-docsify#89]

**Comment by shiffman** [comment]
Let me know there are any questions or anything I can do to help with this!

**Comment by QuinnHe** [comment]
Hi @myrahsa, do you mind helping with this? We can get some suggestions from Dan as well for this :) I can join you on this after I have other model pages ready. Thank you!!

**Comment by QuinnHe** [comment]
Resolved. Close the issue
