### ISSUE TITLE
Hyperlink navigation does not work for content on different tabs in the Glossary. 

### ISSUE THREAD

**Issue by alanvww** [ml5js/ml5-website-v02-docsify#91]
Hi team, while working on the glossary, I noticed that the links between different tabs on the glossary page are not working. For example, when the user clicks on the `underfitting` link in the `overfitting` section, the browser jumps to `.../ml5-glossary?id=underfitting`. Although the URL is changed, the tab does not automatically switch to the new content.

I tried to look over [the issues of docsify-tabs repo](https://github.com/jhildenbiddle/docsify-tabs/issues?q=is:issue+is:closed) but didn't find anything useful. 

Maybe we can keep it this way or make the glossary a long list just for now. @MOQN @QuinnHe

**Comment by MOQN** [comment]
@alanvww Thank you so much for your thoroughness! Let's keep it as it is for now and investigate other methods after the launch.

**Comment by alanvww** [comment]
Fixed in #159
